### ISSUE TITLE
Ejercicio listo para su revisión

### ISSUE THREAD

**Issue by JuanMaRuizH** [DevAppWeb/guess-a-number-JuanMaRuizH#1]
Hola, el ejercicio `guess-a-number-basic` está listo para ser revisado.

Un saludo. 

Muchas gracias.

**Comment by jivanrod** [comment]
Hola Juan Manuel,

 Te adjunto mis comentarios, :

- Te recomiendo simplificar la estructura del código que resuelve estos primeros ejercicios. Dada la poca dificultad de los mismos me inclino más por reducir el número de ficheros necesarios a 2. Por un lado index.php, se encarga de generar el formulario de petición de datos y si quieres mostrar avisos de datos inválidos y por otro lado procesaFormulario.php se encarga de recoger los datos del formulario, procesarlos y generar la página dinámica con los resultados. Quizás en estos primeros ejercicios no conviene complicar mucho el código con el tema de las validaciones de datos con lo que el formulario de recogida de datos de index.php podría ser HTML estático. Si los datos no son correctos puedes optar de momento por abortar la ejecución del script (exit) con un mensaje de error. El script de procesaFormulario tiene una parte inicial programada en PHP donde se lee y procesan los datos y una parte final en HTML con incrustaciones de expresiones de PHP donde se construye la página dinámica. El código HTML solo aparece en la segunda parte del script. No generes HTML en la fase de lectura y proceso de datos.

- Acostúmbrate a utilizar la notación <?= expresionPHP ?> en vez de sentencias echo o print para incrustar la evaluación de expresiones PHP en las páginas dinámicas. Revisa alguna de las soluciones propuestas para encontrar distintos ejemplos de uso. Por ejemplo en tu caso:

```php
<?php
 foreach ($_POST as $key => $value) {
        $key = str_replace("-", " ", $key);
        $formattedStr = ucfirst($key);
        echo "<p>". $formattedStr .": <b>" . $value . "</b></p>";
    }
?>


<?php
foreach ($_POST as $key => $value) { ?>
<p><?=  ucfirst(str_replace("-", " ", $key)) ?>: <b><?= $value ?></b></p>
<?php } ?>
```



- No recomiendo utilizar funciones para generar HTML o extractos de la página dinámica, como en generateMssg, veo mejor que se añada el HTML directamente en la construcción de la página dinámica. Por ejemplo, los mensajes de acierto o fallo pueden implementarse en la página con la ayuda de un operador ternario PHP. Asumiendo que la variable $resultado almacena el resultado de comparar el número de usuario y el número secreto:

```php
<p><?= ($resultado) ? "Has acertado" : "Has fallado" ?></p>
```

**Comment by JuanMaRuizH** [comment]
Hola Jorge, muchas gracias por tus comentarios.

Con respecto a la estructura y tras leer tu comentario me he dado cuenta de que ya lo comentaste en el for de la UT diciendo la estructura general que debían tener los ejercicios (lo he visto tarde, lo siento). En los siguientes ejercicios de la UT02 que no he entregado procuraré hacerlo como propones.

Repasaré el resto de tus comentarios (como no generar código HTML) y aplicarlo también las sucesivas tareas.

Sé que tengo malas costumbres adquiridas, intentaré ir corrigiéndolas. 

Muchas gracias por la revisión.

Un saludo.
JuanMa.

**Comment by jivanrod** [comment]
No te preocupes, el estilo de programación es siempre un tema un tanto personal así que intento argumentar bien las ventajas de los cambios que te voy proponiendo. 
 Sí que veo que poco a poco vas incluyendo nuevos recursos del lenguaje PHP en tus programas y eso es lo importante. 
Ánimo
