### ISSUE TITLE
Segundo ejercicio con sesiones listo para su revisión

### ISSUE THREAD

**Issue by JuanMaRuizH** [DevAppWeb/guess-a-number-JuanMaRuizH#2]
Rama ```https://github.com/DevAppWeb/guess-a-number-JuanMaRuizH/tree/guess-a-number-repeat```

Un saludo.

Muchas gracias

**Comment by jivanrod** [comment]
Hola Juan Manuel,

 Me alegra ver trabajo tuyo de nuevo. Desde luego, se nota que te gusta darle calidad a tus programas. Te envío un par de comentarios pero en términos generales el ejercicio está muy bien resuelto.

* No termina de convencerme que se establezcan mensajes para el usuario en el código del controlador ya que, en mi opinión, provoca que el programador PHP invada el área de trabajo del diseñador del interfaz. Ambas tareas podrían ser realizadas por personas distintas y no deberían solaparse. Yo soy más partidario de establecer flags en el controlador que puedan ser interpretados en las vistas y traducidos a los mensajes de usuario que mejor encajen con la filosofía y diseño del interfaz.

* La función validateUserGuess puede implementarse con el operador de comparación <=> spaceship operator en PHP 7 ([entrada en stackoverflow](https://stackoverflow.com/questions/30365346/what-is-the-spaceship-operator-in-php-7)). En este caso el resultado de comparar los números (0, -1 o +1) sería la información utilizada para saber si ha acertado o no , y en este último caso saber qué mensaje transmitir al jugador.

* La forma de destruir la sesión me parece muy compleja. Pienso que sería suficiente con:

```php
session_unset();
session_destroy();
setcookie(session_name(), '', 0, '/');
```

Saludos

**Comment by JuanMaRuizH** [comment]
Hola Jorge, muchas gracias por tus comentarios. Intento hacer las cosas de la manera más correcta posible aunque no termina de convencerme lo que hago...

Respecto a tus comentarios:

* _mensajes para el usuario en el código del controlador_ Lo he pasado al modelo, no creo que sea del todo correcto, pero tampoco me gustaría meter tanto lógica en la vista y quería dejar ese texto algo aislado del resto.

* _función validateUserGuess_ Desconocía ese comparador 😵 he modificado la función quedando ahora más clara. Muchas gracias.

* _destruir la sesión_ => No ví nada claro esa información en el temario y de decanté por Stackoverflow que me pareció más completa. Pero la solución propuesta es mucho más sencilla y efectiva. Gracias.

Ya están subidos los cambios.

Un saludo.
JM.

**Comment by jivanrod** [comment]
Estupendo, también te recomendaría que ojearas la [solución propuesta](https://github.com/DevAppWeb/guess-a-number-ivandevappweb/blob/guess-a-number-2/index.php) porque quizás te pueda aportar ideas o recursos útiles para incorporar a tu siguiente programa.

Saludos

**Comment by JuanMaRuizH** [comment]
Muchas gracias. Así lo haré.

Un saludo.

JM.
