### ISSUE TITLE
Ejercicio guess-a-number-3 listo para su revisión

### ISSUE THREAD

**Issue by JuanMaRuizH** [DevAppWeb/guess-a-number-JuanMaRuizH#3]
Rama ```guess-a-number-repeat-oo```
Muchas gracias.
Un saludo.

**Comment by jivanrod** [comment]
Hola Juan Manuel,

 Buen ejercicio. Te mando algún comentario.

 * La clase GuessNumber no corresponde al controlador sino al modelo. El objeto de esa clase va a representar los datos y el estado de la aplicación. Quizás ubicarlo en una carpeta que se llame controller da pie a confusión ya que el único controlador es index.php

* No es necesario que cierres la sesión cuando se acabe el juego, puedes simplemente resetear el valor de su entrada 'play'. Tampoco hace falta que recrees el objeto GuessNumber, podrías dotarlo de un método "reset" que reinicializa todos sus valores.

* El controlador debe contemplar todas las posibles peticiones del cliente en el mismo fichero index.html. La petición que tratas en el script Session.php !empty($_POST["reset-game"]) debería pasar a index.html.

* No creo que sea necesario del todo el fichero Session.php. Tal como lo nombras (primera letra mayúscula) parece que estés definiendo una clase. Además el contenido parece un poco mezclado. Quizás tenga sentido un fichero con los mensajes de interfaz.

Para terminar la corrección no dejes de revisar la solución propuesta.

**Comment by JuanMaRuizH** [comment]
Buenos días, muchas gracias por tus comentarios. Totalmente erróneo haber llamado Controller a lo que era el modelo.

Aplicadas las mejoras.

Un saludo y gracias.
JuanMa.
