### ISSUE TITLE
Ejercicio guess-a-number-4 listo para su revision

### ISSUE THREAD

**Issue by JuanMaRuizH** [DevAppWeb/guess-a-number-JuanMaRuizH#4]
Rama ```guess-a-number-repeat-oo-blade```
Muchas gracias.

Un saludo

**Comment by jivanrod** [comment]
Hola Juan Manuel,

 Veo que utilizas el concepto de motor de vistas con bastante soltura. 
Lo veo todo correcto a excepción de que en la vista playResult utilizas a veces la notación <?= exp ?> en vez de {{ exp }}.
 También has utilizado correctamente Composer como gestor de paquetes. 
 Buen trabajo.

**Comment by JuanMaRuizH** [comment]
Buenas tardes.

En esta rama he añadido las mejoras propuestas tanto para la rama anterior como a esta. 

Muchas gracias.
Un saludo.

JuanMa.

**Comment by jivanrod** [comment]
Hola Juan Manuel,

 Esta muy bien. Te incluyo algún comentario.

* El método "setNumberAttempts" no ofrece un parámetro de entrada y lo utilizas como método de reset. Los setters siempre permiten incluir un parámetro para comunicar el valor con el que el objeto puede modificar su propiedad. Para resetear ese valor podemos hace $this->setNumberOfAttempts(0).

* Otra cosilla menor pero que suelo hacer bastante hincapié es en los nombres de los métodos. Cuando utilizas el nombre de "resetGame" parece que el objeto puede resetear Games cuando en realidad se está reseteando **a si mismo** por lo que quizás sea mejor el nombre de la acción en imperativo "reset".

* La apuesta del jugador puede no ser parte del objeto y usarse solamente de parámetro de entrada al método de validación de la apuesta "validateUserGuess"

Buen trabajo, anímate con el ejercicio del ahorcado!!.

**Comment by JuanMaRuizH** [comment]
Buenas tardes Ivan. Gracias por tus comentarios.

Quizá tengas razón, ya que la apuesta del usuario no es constante durante toda la partida sino, que se va actualizando a medida que avanza el juego. No lo había planteado así, pensé en la apuesta del usuario como parte de un todo el juego, pero sin tener en cuenta que es cambiante.

Muchas gracias. 
Un saludo.

JuanMa

Estoy intentando terminar el tic-tac-toe-oo-blade se me está atravesando 😩 Lo siguiente el del ahorcado 😄
